apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blog-ingress
  labels:
    name: blog-ingress
  namespace: blog
  annotations:
    cert-manager.io/issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - www.jssoriao.dev
      secretName: tls-secret
    - hosts:
        - jssoriao.dev
      secretName: root-tls-secret
  rules:
    - host: www.jssoriao.dev
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: blog-service
                port:
                  number: 8080
    - host: jssoriao.dev
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: blog-service
                port:
                  number: 8080
